apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: items-api
  namespace: items-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: items.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: items-api
                port:
                  number: 80
