apiVersion: v1
kind: Secret
metadata:
  name: items-api-secrets
  namespace: items-api
type: Opaque
stringData:
  DATABASE_URL: postgresql://app_user:replace-with-password@replace-with-rds-endpoint:5432/app_db
